version: '3.8'

services:
  ollama-init:
    image: ollama/ollama:latest
    depends_on:
      - ollama-latest
    entrypoint: [ "/bin/sh", "-c", "ollama pull llama3" ]
    volumes:
      - ./ollama:/root/.ollama
    restart: "no"

  codeur-agent-api:
    build: ./
    container_name: codeur-agent-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - ollama-latest
    environment:
      - OLLAMA_HOST=http://ollama-latest:11434

  ollama-latest:
    image: ollama/ollama:latest
    container_name: ollama-latest
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=1h
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
